# Generated by Django 5.0.1 on 2024-01-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlist',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CharLists.alignment'),
        ),
        migrations.AlterField(
            model_name='charlist',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CharLists.background'),
        ),
    ]
