# Generated by Django 5.0.1 on 2024-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/CharLists/img/alignments/'),
        ),
        migrations.AlterField(
            model_name='background',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/CharLists/img/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='charlist',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/CharLists/img/persons/'),
        ),
    ]
