# Generated by Django 5.0.1 on 2024-01-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0002_alter_charlist_alignment_alter_charlist_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlist',
            name='gameRace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CharLists.gamerace'),
        ),
        migrations.AlterField(
            model_name='charlist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/persons/'),
        ),
    ]
