# Generated by Django 5.0.1 on 2024-01-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0003_alter_charlist_gamerace_alter_charlist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/CharLists/img/persons/'),
        ),
    ]
