# Generated by Django 4.2.3 on 2023-08-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='char_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelegency', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('description', models.TextField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.background')),
            ],
        ),
        migrations.CreateModel(
            name='characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='game_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='game_race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.spell')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.skill')),
            ],
        ),
        migrations.CreateModel(
            name='saving_throws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='possessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.possession')),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.language')),
            ],
        ),
        migrations.CreateModel(
            name='game_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.char_list')),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.game_class')),
            ],
        ),
        migrations.AddField(
            model_name='char_list',
            name='game_class_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.game_class'),
        ),
        migrations.AddField(
            model_name='char_list',
            name='game_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.game_race'),
        ),
        migrations.AddField(
            model_name='char_list',
            name='alignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharLists.alignment'),
        ),
    ]
