# Generated by Django 4.2.4 on 2023-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0003_char_list_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char_list',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='img/persons/', width_field=100),
        ),
    ]
