# Generated by Django 4.2.4 on 2023-10-01 12:02
# 
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0004_alter_char_list_img'),
    ]

    operations = [
            migrations.RenameModel('game_class'   , 'gameClass'),
            migrations.RenameModel('game_race'    , 'gameRace'),
            migrations.RenameModel('char_list'    , 'charList'),
            migrations.RenameModel('saving_throws', 'savingThrows'),
            migrations.RenameModel('game_classes' , 'gameClasses'),

            
    ]
