# Generated by Django 4.2.4 on 2023-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharLists', '0005_auto_20231001_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charlist',
            old_name='game_class_main',
            new_name='gameClassMain',
        ),
        migrations.RenameField(
            model_name='charlist',
            old_name='game_race',
            new_name='gameRace',
        ),
        migrations.RenameField(
            model_name='gameclasses',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.RenameField(
            model_name='gameclasses',
            old_name='game_class',
            new_name='gameClass',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.RenameField(
            model_name='possessions',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.RenameField(
            model_name='savingthrows',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.RenameField(
            model_name='spells',
            old_name='char_list',
            new_name='charList',
        ),
        migrations.AlterField(
            model_name='gameclass',
            name='title',
            field=models.CharField(max_length=101),
        ),
    ]
